matrix:
  include:
    - language: python
      python: "3.8"
      # command to install dependencies

      before_script:
        - cd back-end
      install:
        - pip install -r requirements.txt
      script:
        - src/manage.py test

    - language: node_js
      node_js:
        - "13.7.0"
      addons:
        chrome: stable
      before_script:
        - cd front-end/instagram
        - npm install
      script:
        - npm test
