matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      addons:
        chrome: stable
      before_script:
        - cd front-end/instagram
        - npm install
      script:
        - npm test
    - language: python
      python:
        - "3.8.1"
      services:
        - mysql
      env:
        -DJANGO=3.0.2 DB=mysql
      before_script:
        - cd back-end
        - pip install -r requirements.txt
        - cd src
      script:
        - python manage.py test
      