language: python
python: "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: -(cd front-end && cd instagram && npm test)
  - (cd back-end && cd py.test)
