matrix:
include:
- language: node_js
node_js:
- "13.7.0"
addons:
chrome: stable
before_script:
- cd front-end/instagram
- npm install
script:
- npm test
include:
- language: python
python: "3.8.1"
script:
manage.py test