matrix:
  include:
    - language: python
      python: "3.8"
      # command to install dependencies
      install:
        - cd back-end
        - pip install -r requirements.txt
        - pip install -q Django==$DJANGO_VERSION
        - python setup.py -q install
        env:
        - DJANGO_VERSION=3.0.2
      virtualenv:
       system_site_packages: true
        before_script:
        -cd src
      script:
        manage.py test

    - language: node_js
      node_js:
        - "13.7.0"
      addons:
        chrome: stable
      before_script:
        - cd front-end/instagram
        - npm install
      script:
        - npm test
