matrix:
include:
- language: python
python: "3.8.1"

#dependencies
install:
- pip install autopep8
- pip install django
- pip install djangorestframework
- pip install mysqlclient
- pip install pillow
- pip install django-cors-headers
- pip install mysql
- pip install asgiref
- pip install pytz
- pip install sqlparse
- pip install virtualenv
- python setup.py -q install

before_script:
-cd back-end
-cd src
script:
-env\Scripts\activate
manage.py test
- language: node_js
node_js:
- "13.7.0"
addons:
chrome: stable
before_script:
- cd front-end/instagram
- npm install
script:
- npm test
