matrix:
  include:
    - language: node_js
      node_js:
        - "13.7.0"
      addons:
        chrome: stable
      before_script:
        - cd front-end/instagram
        - npm install
      script:
        - npm test
