matrix:
  include:
    - language: node_js, python
      python:
        - "2.7.17"
      env:
        - SECRET_KEY='TEST'
      services: 
        - 
      install: 
        - pipenv install
      script: 
        - python manage.py test
      node_js:
        - "13.7.0"
      addons:
        chrome: stable
      before_script:
        - cd front-end/instagram
        - npm install
      script:
        - npm test
