matrix:
include:
- language: python
python: "3.8"
before_script:
-cd back-end
- cd src
#dependencies
install:
- pip install autopep8
- pip install django
- pip install djangorestframework
- pip install mysqlclient
- pip install pillow
- pip install django-cors-headers
- pip install mysql
- pip install asgiref
- pip install pytz
- pip install sqlparse
- pip install virtualenv
- pip install -q Django == $DJANGO_VERSION
- python setup.py -q install
env: 
- DJANGO_VERSION = 3.0.2
virtualenv:
system_site_packages: true
script:
manage.py test

- language: node_js
  node_js:
        - "13.7.0"
      addons:
        chrome: stable
      before_script:
        - cd front-end/instagram
        - npm install
      script:
        - npm test
