matrix:
include:
  - language: node_js & python
  
node_js:
  - "13.7.0"
python:
-"3.8.1"
addons:
chrome: stable
before_script:
  - cd front-end/instagram
  - npm install
script:
  - npm test
before_script:
-cd back-end
-cd src
script:
  - pytest
